name: xcube-stac
channels:
  - conda-forge
dependencies:
  # Required
  - python >=3.10
  - boto3 ==1.37.3
  - cftime
  - dask
  - h5netcdf
  - libgdal-jp2openjpeg
  - libgdal-netcdf
  - numpy
  - pandas
  - planetary-computer
  - pyproj
  - pystac
  - pystac-client
  - rasterio
  - requests
  - rioxarray
  - xarray
  - xmltodict
  - xcube >=1.11.0
  # Development Dependencies - Tools
  - black
  - isort
  - pytest
  - pytest-cov
  - pytest-recording
  - ruff
  # Development Dependencies - Demos
  - jupyterlab
  - matplotlib